name: one

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Cache somefile.txt
        id: cache-somefile
        uses: actions/cache@v4
        with:
          path: somefile.txt
          key: somefile-${{ runner.os }}-v1

      - name: Create somefile.txt if cache miss
        if: steps.cache-somefile.outputs.cache-hit != 'true'
        run: |
          date > somefile.txt

      - name: Show contents of somefile.txt
        run: cat somefile.txt

      - name: Run a one-line script
        run: echo "Hello world!"
